### ISSUE TITLE
点击拍照搜提后报错，华为mate10 pro,BLA-AL00,EMUI9.1.0

### ISSUE THREAD

**Issue by tinyvampirepudge** [wangtaoT/AndroidOCR#13]
2019-10-16 12:03:31.657 16771-16771/com.wt.ocr I/PermissionManager: camera remind result:true
2019-10-16 12:03:31.661 16771-16771/com.wt.ocr E/SurfaceView: Exception configuring surface
    java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2174)
        at com.wt.ocr.camear.CameraPreview.updateCameraParameters(CameraPreview.java:203)
        at com.wt.ocr.camear.CameraPreview.surfaceCreated(CameraPreview.java:101)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:746)
        at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:154)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:993)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2704)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
        at android.view.Choreographer.doCallbacks(Choreographer.java:893)
        at android.view.Choreographer.doFrame(Choreographer.java:812)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

**Comment by wangtaoT** [comment]
已增加sd卡权限
